### ISSUE TITLE
Replace "infinite" as an attribute instead of a class

### ISSUE THREAD

**Issue by kitze** [720kb/angular-fx#10]
I think it would be better if "infinite" is an attribute directive like 

`<a href="#" ngfx-fade-out="3 > 2" ngfx-infinite>Fadeout</a>`

instead of 

`<a href="#" ngfx-fade-out="3 > 2" class="infinite">Fadeout</a>`

**Comment by 45kb** [comment]
@kitze Hi, thank you for the issue, i personally 100% agree with you, if you can feel free to PR it, or we will make it but a litte bit later unfortunately
