### ISSUE TITLE
Shake not working

### ISSUE THREAD

**Issue by cyrixmorten** [720kb/angular-fx#15]
I found that

```
ngfx-shake="ctrl.someCondition"
```

Does not work, wheras 

```
ngfx-bounce="ctrl.someCondition"
```

does work.

Looks like there is some statements missing in the helper css file perhaps as `angular-fx.css` does not contain any keywords matching ´shake´.

Not that big of a deal, just wasted quite some some as I thought I was missing some dependency or the like and debugged the shake directive to confirm that it was indeed triggered.

**Comment by 45kb** [comment]
Ops, must be an oversight, thanks for spotting this out :+1: 

We will surely fix it asap, if you want to PR feel free.

**Comment by cyrixmorten** [comment]
Great :) impressively fast response.

Now that I have your attention, just wanted to point out that while looking through the source code, I noticed that your directives could be greatly simplified.

Taking wobble as an example:

```
.directive('ngfxWobble', [function directiveFunction() {
      return {
        'restrict': 'A',
        'link': function linkingFunction(scope, element, attributes) {
          var c = 'ngfx-wobble-start animated wobble'
            , fx = function fxFunction() {
              if (scope.$eval(attributes.ngfxWobble)) {
                element.removeClass('animated').addClass(c);
              } else {
                element.removeClass(c);
              }
           };

          scope.$watch(attributes.ngfxWobble, function watctherFunction() {
            fx();
          });
        }
      };
    }])
```

Could be simplified to: 

```
.directive('ngfxWobble', [function directiveFunction() {
     return {
        'restrict': 'A',
        'link': function linkingFunction(scope, element, attributes) {
          scope.$watch(attributes.ngfxWobble, function watctherFunction() {
            element.toggleClass('ngfx-wobble-start animated wobble', scope.$eval(attributes.ngfxWobble));
          });
        }
      };
    }])
```

**Comment by 45kb** [comment]
@cyrixmorten  Hi i've tested out and it seems that shake works great check here http://plnkr.co/edit/8oNRgSPbilO6WZhiTt1A?p=preview

Be sure to install latest version of the files better with bower or npm install.

As for the code suggestion, yes that would be really cool to slim it down, i will try to do all but if you want to make it feel free to PR it. :+1: 

Going to close the issue for the moment.

**Comment by cyrixmorten** [comment]
Alright, thank you for the response. 

I might not have correctly included everything. However, I am pretty sure that my equivalent animate.css did not look like the one you supplied in your plnkr. 

I will check back up on it monday or tuesday when I get back to my working PC. 

Just for info, I installed your library through npm.

Regarding the slim-down refactor, I don't think it is that important or anything, was simply in case you had not noticed that 'shortcut' :)

**Comment by cyrixmorten** [comment]
Investigated the matter and found that I did not properly include animate.css.

Thank you again for taking the time to look at my issue and will definitely contribute if I find the time for it :)
